### ISSUE TITLE
Animations stop when pressing "load saved game"

### ISSUE THREAD

**Issue by pieman12123415** [raptorcode/Annex#10]
When I am on the main menu, and press on the load saved game button before the sliding animation is over, the animation stops.

**"ayy lmao"**

**Comment by raptorcode** [comment]
This is a browser based issue - using the built-in prompt() method for asking the user for text input stops execution of animations and script until the user has entered a value, meaning that the problem is impossible to "fix" without moving away from the convenient built-in prompt() method.

Custom popup windows are a possible feature in the future, but definitely not highest priority.
